"use client";

import { Check, Lightbulb, RefreshCw, ShieldCheck, X } from "lucide-react";
import Link from "next/link";
import { useState, useTransition } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type Plan = { headline: string; insight: string; action: string; citations: Array<{ id: string; label: string; detail: string }> };

export function WeeklyFinancialPlan({ receiptCount }: { receiptCount: number }) {
  const [plan, setPlan] = useState<Plan | null>(null);
  const [message, setMessage] = useState("");
  const [decision, setDecision] = useState<"accepted" | "dismissed" | null>(null);
  const [isPending, startTransition] = useTransition();

  function generatePlan() {
    setMessage("");
    setDecision(null);
    startTransition(async () => {
      const response = await fetch("/api/weekly-plan", { method: "POST" });
      const body = await response.json().catch(() => null);
      if (!response.ok || !body?.plan) {
        setPlan(null);
        setMessage(body?.error ?? "ReceiptBrain could not create an action plan right now.");
        return;
      }
      setPlan(body.plan);
    });
  }

  return <Card className="overflow-hidden"><CardHeader className="border-b bg-gradient-to-r from-emerald-500/10 via-primary/10 to-transparent"><CardTitle className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-emerald-600 text-white"><Lightbulb className="size-5" /></span>Weekly Financial Action Plan</CardTitle><p className="text-sm leading-6 text-muted-foreground">One practical next step, generated by GPT-5.6 from your private receipt history.</p></CardHeader><CardContent className="space-y-5 pt-6">{!plan && !message && <p className="rounded-lg border border-dashed bg-muted/30 p-4 text-sm leading-6 text-muted-foreground">{receiptCount ? `Ready to reflect on ${receiptCount} recent receipt${receiptCount === 1 ? "" : "s"}.` : "Upload and verify a receipt before creating your first action plan."}</p>}{plan && <div className="space-y-5 rounded-xl border bg-muted/30 p-5"><div><p className="text-xs font-medium uppercase tracking-[0.16em] text-emerald-700 dark:text-emerald-400">This week</p><h2 className="mt-2 text-xl font-semibold tracking-tight">{plan.headline}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{plan.insight}</p></div><div className="rounded-lg bg-background p-4"><p className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">Try this</p><p className="mt-2 text-sm font-medium leading-6">{plan.action}</p></div><div><p className="flex items-center gap-1.5 text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground"><ShieldCheck className="size-3.5 text-primary" />Evidence from your receipts</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{plan.citations.map((citation) => <Link key={citation.id} href={`/documents/${citation.id}`} className="rounded-lg border bg-background p-3 text-sm hover:bg-muted"><span className="font-medium">{citation.label}</span><span className="mt-1 block text-muted-foreground">{citation.detail}</span></Link>)}</div></div>{decision ? <p className="flex items-center gap-2 text-sm font-medium text-emerald-700 dark:text-emerald-400">{decision === "accepted" ? <Check className="size-4" /> : <X className="size-4" />}{decision === "accepted" ? "Action plan accepted for this week." : "Action plan dismissed. Generate another when you are ready."}</p> : <div className="flex flex-wrap gap-2"><Button type="button" onClick={() => setDecision("accepted")}><Check className="size-4" />I’ll try this</Button><Button type="button" variant="outline" onClick={() => setDecision("dismissed")}><X className="size-4" />Not this week</Button></div>}</div>}{message && <p className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-800 dark:text-amber-300">{message}</p>}<Button type="button" onClick={generatePlan} disabled={!receiptCount || isPending}><RefreshCw className={isPending ? "size-4 animate-spin" : "size-4"} />{isPending ? "Creating your plan..." : plan ? "Create another plan" : "Create my weekly plan"}</Button></CardContent></Card>;
}
